// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.product;

public interface ListProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:products.ListProducts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .products.ProductResponse products = 1;</code>
   */
  java.util.List<com.dmsc.service.model.product.ProductResponse> 
      getProductsList();
  /**
   * <code>repeated .products.ProductResponse products = 1;</code>
   */
  com.dmsc.service.model.product.ProductResponse getProducts(int index);
  /**
   * <code>repeated .products.ProductResponse products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .products.ProductResponse products = 1;</code>
   */
  java.util.List<? extends com.dmsc.service.model.product.ProductResponseOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .products.ProductResponse products = 1;</code>
   */
  com.dmsc.service.model.product.ProductResponseOrBuilder getProductsOrBuilder(
      int index);
}
