// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.product;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:products.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 price = 3;</code>
   * @return The price.
   */
  long getPrice();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string category = 5;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 5;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>int32 availability = 6;</code>
   * @return The availability.
   */
  int getAvailability();
}
