// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.product;

public interface ProductStockQuantityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:products.ProductStockQuantity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 quantity = 2 [(.buf.validate.field) = { ... }</code>
   * @return The quantity.
   */
  int getQuantity();
}
