// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .orders.OrderProduct products = 3;</code>
   */
  java.util.List<com.dmsc.service.model.order.OrderProduct> 
      getProductsList();
  /**
   * <code>repeated .orders.OrderProduct products = 3;</code>
   */
  com.dmsc.service.model.order.OrderProduct getProducts(int index);
  /**
   * <code>repeated .orders.OrderProduct products = 3;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .orders.OrderProduct products = 3;</code>
   */
  java.util.List<? extends com.dmsc.service.model.order.OrderProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .orders.OrderProduct products = 3;</code>
   */
  com.dmsc.service.model.order.OrderProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>.orders.ORDER_STATUS status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.orders.ORDER_STATUS status = 4;</code>
   * @return The status.
   */
  com.dmsc.service.model.order.ORDER_STATUS getStatus();

  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 6;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 6;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
