// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

/**
 * Protobuf enum {@code orders.ORDER_STATUS}
 */
public enum ORDER_STATUS
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PENDING = 0;</code>
   */
  PENDING(0),
  /**
   * <code>PROCESSING = 1;</code>
   */
  PROCESSING(1),
  /**
   * <code>SENT = 2;</code>
   */
  SENT(2),
  /**
   * <code>RECEIVED = 3;</code>
   */
  RECEIVED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PENDING = 0;</code>
   */
  public static final int PENDING_VALUE = 0;
  /**
   * <code>PROCESSING = 1;</code>
   */
  public static final int PROCESSING_VALUE = 1;
  /**
   * <code>SENT = 2;</code>
   */
  public static final int SENT_VALUE = 2;
  /**
   * <code>RECEIVED = 3;</code>
   */
  public static final int RECEIVED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ORDER_STATUS valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ORDER_STATUS forNumber(int value) {
    switch (value) {
      case 0: return PENDING;
      case 1: return PROCESSING;
      case 2: return SENT;
      case 3: return RECEIVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ORDER_STATUS>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ORDER_STATUS> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ORDER_STATUS>() {
          public ORDER_STATUS findValueByNumber(int number) {
            return ORDER_STATUS.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dmsc.service.model.order.OrderProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ORDER_STATUS[] VALUES = values();

  public static ORDER_STATUS valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ORDER_STATUS(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:orders.ORDER_STATUS)
}

