// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

public interface OrderProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.OrderProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int64 quantity = 2;</code>
   * @return The quantity.
   */
  long getQuantity();

  /**
   * <code>.orders.ORDER_STATUS status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.orders.ORDER_STATUS status = 3;</code>
   * @return The status.
   */
  com.dmsc.service.model.order.ORDER_STATUS getStatus();
}
