// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

public interface OrderStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.OrderStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.orders.ORDER_STATUS status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.orders.ORDER_STATUS status = 2;</code>
   * @return The status.
   */
  com.dmsc.service.model.order.ORDER_STATUS getStatus();
}
