// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

public interface OrderItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.OrderItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
