// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_service.proto

// Protobuf Java Version: 3.25.3
package com.dmsc.service.model.order;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_CreateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_OrderProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_OrderProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_OrderItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_OrderItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_OrderStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_OrderStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023order_service.proto\022\006orders\032\037google/pr" +
      "otobuf/timestamp.proto\"M\n\022CreateOrderReq" +
      "uest\022&\n\010products\030\001 \003(\0132\024.orders.OrderPro" +
      "duct\022\017\n\007user_id\030\002 \001(\t\"\332\001\n\rOrderResponse\022" +
      "\n\n\002id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022&\n\010products" +
      "\030\003 \003(\0132\024.orders.OrderProduct\022$\n\006status\030\004" +
      " \001(\0162\024.orders.ORDER_STATUS\022.\n\ncreated_at" +
      "\030\005 \001(\0132\032.google.protobuf.Timestamp\022.\n\nup" +
      "dated_at\030\006 \001(\0132\032.google.protobuf.Timesta" +
      "mp\"Z\n\014OrderProduct\022\022\n\nproduct_id\030\001 \001(\t\022\020" +
      "\n\010quantity\030\002 \001(\003\022$\n\006status\030\003 \001(\0162\024.order" +
      "s.ORDER_STATUS\"\027\n\tOrderItem\022\n\n\002id\030\001 \001(\t\"" +
      "?\n\013OrderStatus\022\n\n\002id\030\001 \001(\t\022$\n\006status\030\002 \001" +
      "(\0162\024.orders.ORDER_STATUS*C\n\014ORDER_STATUS" +
      "\022\013\n\007PENDING\020\000\022\016\n\nPROCESSING\020\001\022\010\n\004SENT\020\002\022" +
      "\014\n\010RECEIVED\020\0032\307\001\n\014OrderService\022@\n\013Create" +
      "Order\022\032.orders.CreateOrderRequest\032\025.orde" +
      "rs.OrderResponse\0224\n\010GetOrder\022\021.orders.Or" +
      "derItem\032\025.orders.OrderResponse\022?\n\021Update" +
      "OrderStatus\022\023.orders.OrderStatus\032\025.order" +
      "s.OrderResponseBR\n\034com.dmsc.service.mode" +
      "l.orderB\nOrderProtoP\001Z$github.com/qwerty" +
      "di/playground/pb/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_orders_CreateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_CreateOrderRequest_descriptor,
        new java.lang.String[] { "Products", "UserId", });
    internal_static_orders_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orders_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_OrderResponse_descriptor,
        new java.lang.String[] { "Id", "UserId", "Products", "Status", "CreatedAt", "UpdatedAt", });
    internal_static_orders_OrderProduct_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_orders_OrderProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_OrderProduct_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "Status", });
    internal_static_orders_OrderItem_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_orders_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_OrderItem_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_orders_OrderStatus_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_orders_OrderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_OrderStatus_descriptor,
        new java.lang.String[] { "Id", "Status", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
